name: intrale
description: Integridad, Trascendencia y Lealtad


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
 
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  random_pk: any
  shimmer: ^2.0.0
  transparent_image: ^2.0.0
  flutter_slidable: ^0.6.0
  flutter_rating: ^0.0.2
  http: ^0.13.4
  #giffy_dialog: ^1.3.0
  json_annotation: ^4.3.0
  uuid: ^3.0.4
  provider: ^6.0.1
  shared_preferences: ^2.0.5
  intl: ^0.17.0
  flutter_i18n: ^0.30.0
  intrale_mobile_mercadopago: ^0.0.8
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  json_serializable: ^6.0.1

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  generate: false

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

    # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  #plugin:
   # platforms:
    #  android:
     #   package: ar.com.intrale.mobile
      #  pluginClass: MercadoPagoPlugin
      #ios:
        #pluginClass: HelloPlugin

  fonts:
    - family: Sans
      fonts:
        - asset: assets/font/OpenSans-Bold.ttf
          weight: 800
        - asset: assets/font/OpenSans-Semibold.ttf
          weight: 600
        - asset: assets/font/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/font/OpenSans-Light.ttf
          weight: 200
    - family : Popins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-SemiBold.ttf
          weight : 600
    - family : Berlin
      fonts:
        - asset: assets/font/BRLNSDB.TTF
          weight: 700
    - family : Gotik
      fonts:
        - asset: assets/font/GOTHIC.TTF
          weight: 400
        - asset: assets/font/GOTHICB.TTF
          weight : 600

  assets:
    - assets/custom/custom.json
    - assets/flutter_i18n/
    - assets/img/googlewallet.png
    - assets/img/credit.png
    - assets/img/handshake.png
    - assets/img/paypal.png
    - assets/img/icon_facebook.png
    - assets/img/Logo.png
    - assets/img/Rectangle.png
    - assets/img/girl.png
    - assets/img/loginscreenbackground.png
    - assets/img/backgroundgirl.png
    - assets/img/man.png
    - assets/img/search.png
    - assets/img/search2.png
    - assets/img/chat.png
    - assets/img/notifications-button.png
    - assets/img/baner1.png
    - assets/img/baner2.png
    - assets/img/baner3.png
    - assets/img/baner4.png
    - assets/img/baner12.png
    - assets/icon/book.png
    - assets/icon/camera.png
    - assets/icon/fashion.png
    - assets/icon/food.png
    - assets/icon/game.png
    - assets/icon/handphone.png
    - assets/icon/health.png
    - assets/icon/mesin.png
    - assets/icon/otomotif.png
    - assets/icon/pc.png
    - assets/icon/sport.png
    - assets/icon/ticket.png
    - assets/icon/language.png
    - assets/imgItem/fashion1.jpg
    - assets/img/notmessage.png
    - assets/img/noNotification.png
    - assets/img/womanface.jpg
    - assets/icon/truck.png
    - assets/icon/chat.png
    - assets/icon/notification.png
    - assets/icon/callcenter.png
    - assets/icon/setting.png
    - assets/icon/aboutapp.png
    - assets/icon/shopping-cart.png
    - assets/icon/message.png
    - assets/img/house.png
    - assets/img/order.png
    - assets/img/payment.png
    - assets/icon/girlcallcenter.png
    - assets/img/checklist.png
    - assets/icon/creditAcount.png
    - assets/img/creditCardVisa.png
    - assets/img/SliderLogin2.png
    - assets/img/SliderLogin3.png
    - assets/img/SliderLogin4.png
    - assets/imgIllustration/IlustrasiCart.png
    

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
